# Generated by Django 4.2.6 on 2023-10-12 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0002_alter_image_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pepople_cnt", models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name="image",
            name="personal",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="personal.personal",
            ),
        ),
    ]
