# Generated by Django 4.2.6 on 2023-10-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0003_personal_image_personal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="personal",
        ),
    ]
