# Generated by Django 4.2.6 on 2023-10-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0004_remove_image_personal"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Personal",
        ),
    ]
